export const CONTENT_VERSION='tf-content-candidates-v1';
export const CONTENT_STATUSES=Object.freeze(['DRAFT','DEVELOPMENT_REVIEW','SAFETY_REVIEW','APPROVED','PUBLISHED','RETIRED']);
const AGE_BANDS=new Set(['10–12','13–15']);
const LEVELS=[1,2,3];
const PROHIBITED_MOVEMENT_TAGS=new Set(['on-ice','butterfly-drop','rvh-drop','pad-slide','dive','collision','weighted-neck']);

const object=value=>value&&typeof value==='object'&&!Array.isArray(value);
const text=(value,label)=>{if(typeof value!=='string'||!value.trim())throw new Error(`${label} is required.`);};
const list=(value,label,min=1)=>{if(!Array.isArray(value)||value.length<min)throw new Error(`${label} is required.`);};
const review=value=>object(value)&&typeof value.reviewerId==='string'&&value.reviewerId.length>0&&typeof value.reviewedAt==='string'&&Number.isFinite(Date.parse(value.reviewedAt));

export function validateActivityVersion(value){
 if(!object(value))throw new Error('Activity version is required.');
 for(const [key,label] of [['activityId','Activity ID'],['familyId','Family ID'],['name','Name'],['developmentPurpose','Development purpose'],['setup','Setup'],['startingPosition','Starting position'],['commonMistake','Common mistake'],['easierVersion','Easier version'],['harderVersion','Harder version'],['painStopRule','Pain stop rule'],['visualAssetId','Visual asset ID'],['caption','Caption'],['altText','Alt text']])text(value[key],label);
 if(!Number.isInteger(value.version)||value.version<1)throw new Error('Activity version must be a positive integer.');
 list(value.technicalSkillIds,'Technical skill IDs');if(value.technicalSkillIds.some(id=>!Number.isInteger(id)||id<1||id>30))throw new Error('Technical skill IDs must use the canonical 1–30 taxonomy.');
 list(value.attributeIds,'Attribute IDs');
 if(!object(value.eligibility))throw new Error('Eligibility is required.');
 list(value.eligibility.ageBands,'Age eligibility');if(value.eligibility.ageBands.some(item=>!AGE_BANDS.has(item)))throw new Error('Age eligibility contains an unsupported band.');
 list(value.eligibility.levels,'Development levels');if(value.eligibility.levels.some(item=>!LEVELS.includes(item)))throw new Error('Development levels must be Level 1, 2, or 3.');
 if(value.context!=='off-ice')throw new Error('Only off-ice content is allowed.');
 list(value.movementSteps,'Movement steps',2);if(value.movementSteps.some(item=>typeof item!=='string'||!item.trim()))throw new Error('Movement steps must be specific.');
 list(value.primaryCues,'Primary cues');if(value.primaryCues.length>2)throw new Error('Primary cues may contain no more than two cues.');
 list(value.safetyConsiderations,'Safety considerations');
 list(value.substitutions,'Substitutions');
 if(!object(value.prescriptions))throw new Error('Level 1 prescription is required.');
 for(const level of LEVELS){
  const item=value.prescriptions[level];if(!object(item))throw new Error(`Level ${level} prescription is required.`);
  text(item.repsOrTime,`Level ${level} reps or time`);text(item.successCondition,`Level ${level} success condition`);text(item.resultType,`Level ${level} result type`);text(item.resultUnit,`Level ${level} result unit`);
  if(!Number.isInteger(item.rounds)||item.rounds<1||!Number.isInteger(item.restSeconds)||item.restSeconds<0||!Number.isInteger(item.estimatedMinutes)||item.estimatedMinutes<1)throw new Error(`Level ${level} dose is invalid.`);
  if(!object(item.plausibility)||!Number.isFinite(item.plausibility.min)||!Number.isFinite(item.plausibility.max)||item.plausibility.min<0||item.plausibility.max<item.plausibility.min)throw new Error(`Level ${level} plausibility is invalid.`);
 }
 list(value.movementTags,'Movement tags');if(value.movementTags.some(tag=>PROHIBITED_MOVEMENT_TAGS.has(tag)))throw new Error('Activity contains a prohibited movement tag.');
 if(!CONTENT_STATUSES.includes(value.contentStatus))throw new Error('Content status is invalid.');
 if(value.contentStatus==='PUBLISHED'&&(!review(value.developmentReview)||!review(value.safetyReview)||typeof value.publishedAt!=='string'||!Number.isFinite(Date.parse(value.publishedAt))))throw new Error('Published activity requires development and safety review.');
 return value;
}

export function isPublishedActivity(value){
 try{return validateActivityVersion(value).contentStatus==='PUBLISHED'&&value.retiredAt==null;}catch{return false;}
}

export function publishedActivityRows(catalog){
 return catalog.filter(isPublishedActivity).map(item=>({activityId:item.activityId,version:item.version,familyId:item.familyId,payloadJson:JSON.stringify(item),contentStatus:item.contentStatus,developmentReviewerId:item.developmentReview.reviewerId,developmentReviewedAt:item.developmentReview.reviewedAt,safetyReviewerId:item.safetyReview.reviewerId,safetyReviewedAt:item.safetyReview.reviewedAt,publishedAt:item.publishedAt,retiredAt:item.retiredAt??null,retirementReason:item.retirementReason??null}));
}

const sources=['https://www.cdc.gov/physical-activity-education/guidelines/index.html','https://www.usahockey.com/agespecifictraining'];
const prescription=(reps,rounds,rest,minutes,success,unit='attempts')=>({repsOrTime:reps,rounds,restSeconds:rest,estimatedMinutes:minutes,successCondition:success,resultType:'attempt-count',resultUnit:unit,plausibility:{min:1,max:rounds*20}});
const candidate=(id,{name,purpose,skills,attributes=['MOVE'],equipment=[],space=['small-indoor'],tags=['standing','controlled'],setup,start,steps,cues,mistake,easier,harder,safety,substitution,level1,level2,level3})=>validateActivityVersion({
 activityId:id,version:1,familyId:id,name,developmentPurpose:purpose,technicalSkillIds:skills,attributeIds:attributes,eligibility:{ageBands:['10–12','13–15'],levels:[1,2,3]},equipment,space,context:'off-ice',movementTags:tags,
 setup,startingPosition:start,movementSteps:steps,prescriptions:{1:level1,2:level2,3:level3},primaryCues:cues,commonMistake:mistake,easierVersion:easier,harderVersion:harder,
 substitutions:[substitution||{id:`${id}-reduced`,whenEquipmentMissing:equipment,whenSpaceMissing:space,equipment:[],space:['small-indoor'],setup:easier}],safetyConsiderations:safety,painStopRule:'Stop immediately if anything hurts, feels dizzy, or loses safe control. Tell an adult.',visualAssetId:`candidate:${id}:v1`,caption:`Candidate setup, action, and balanced finish for ${name}.`,altText:`Three candidate instruction frames show the setup, controlled action, and safe finish for ${name}.`,
 contentStatus:'DEVELOPMENT_REVIEW',developmentReview:null,safetyReview:null,publishedAt:null,retiredAt:null,retirementReason:null,sourceReferences:sources,
});

const three=(a,b,c)=>[a,b,c];
const base={
 'ready-stance-hold':{name:'Balanced ready stance',purpose:'Build a repeatable balanced starting position.',skills:[1,2],setup:'Clear a dry floor area and place one flat marker in front.',start:'Stand behind the marker with feet comfortable, knees soft, head level, and hands visible.',steps:three('Settle into the stance without dropping to the floor.','Hold while breathing normally.','Stand tall, reset, and check that both feet stayed quiet.'),cues:['Head level.','Finish balanced.'],mistake:'Sitting too low or holding the breath.',easier:'Use a slightly taller stance and shorter hold.',harder:'Add a small controlled weight shift without moving the feet.',safety:['Use a dry non-slip floor.','Do not force a deep knee bend.'],level1:prescription('10-second hold',2,20,3,'Hold comfortably and finish balanced.','seconds'),level2:prescription('15-second hold',3,20,4,'Hold comfortably with quiet feet.','seconds'),level3:prescription('20-second hold',3,25,5,'Maintain the same position through a small visual cue change.','seconds')},
 'quiet-side-steps':{name:'Quiet side steps',purpose:'Practice controlled lateral footwork and balanced stops.',skills:[2,3],equipment:['cones'],setup:'Place two flat markers one comfortable step apart on a dry floor.',start:'Stand centered between the markers in a tall ready position.',steps:three('Step to one marker without crossing the feet.','Bring the other foot underneath the body.','Stop balanced, then repeat to the other side.'),cues:['Quiet feet.','Stop under control.'],mistake:'Feet crossing or the body leaning past the outside foot.',easier:'Use one smaller step each way without markers.',harder:'Use two controlled steps each way and stop on an adult hand signal.',safety:['Use flat markers that cannot roll.','Reduce the distance if balance changes.'],level1:prescription('4 trips each way',2,30,4,'Every stop is balanced.'),level2:prescription('5 trips each way',3,30,5,'Feet remain quiet through each stop.'),level3:prescription('6 signaled trips each way',3,35,6,'Respond to the signal without crossing the feet.')},
 'single-leg-balance':{name:'Supported single-leg balance',purpose:'Develop steady balance with an immediate support option.',skills:[2],equipment:['wall-space'],setup:'Choose a clear spot beside a solid wall with nothing underfoot.',start:'Stand tall close enough to touch the wall with one fingertip.',steps:three('Lift one foot just above the floor.','Keep eyes on one fixed point and breathe normally.','Put the foot down before switching sides.'),cues:['Hips level.','Put your foot down before control is lost.'],mistake:'Closing the eyes or fighting through a large wobble.',easier:'Keep one fingertip on the wall for the full hold.',harder:'Remove the fingertip only while the body stays still.',safety:['Use the wall for support before balance is lost.','Do not close the eyes.'],level1:prescription('10 seconds each side',2,25,3,'Each hold ends under control.','seconds'),level2:prescription('15 seconds each side',2,30,4,'Hips stay level on both sides.','seconds'),level3:prescription('20 seconds each side',3,30,5,'Complete each hold with only light support.','seconds')},
 'small-jump-quiet-land':{name:'Small jump quiet landing',purpose:'Practice low-height takeoff and controlled two-foot landing.',skills:[4,5],equipment:['cones'],setup:'Place one flat marker on a dry floor with clear headroom; an adult watches the landing.',start:'Stand behind the marker with feet comfortable and knees soft.',steps:three('Bend a little at the hips and knees.','Make a small two-foot jump without chasing height.','Land on both feet, hold for two seconds, then reset.'),cues:['Land quietly.','Knees follow toes.'],mistake:'Jumping higher after a good rep or letting knees fall inward.',easier:'Rise onto the toes and settle without leaving the floor.',harder:'Jump a small distance forward and hold the same quiet landing.',safety:['No boxes, furniture, or hard-floor knee drops.','Stop when landings become noisy or unsteady.'],level1:prescription('3 jumps',2,45,4,'Hold every landing for two seconds.'),level2:prescription('4 jumps',3,50,5,'Land quietly with knees aligned.'),level3:prescription('5 small directional jumps',3,60,6,'Keep landing quality after the direction cue.')},
 'chair-sit-stand':{name:'Chair sit and stand',purpose:'Practice controlled bodyweight strength through a familiar range.',skills:[7],equipment:[],setup:'Place a sturdy non-rolling chair against a wall on a dry floor.',start:'Stand just in front of the chair with feet comfortable and arms forward.',steps:three('Move hips back slowly toward the chair.','Touch or sit on the seat without dropping.','Stand tall while knees continue to follow the toes.'),cues:['Move slowly.','Keep breathing.'],mistake:'Dropping quickly to the chair or using a rolling chair.',easier:'Sit fully and use light hand support to stand.',harder:'Touch the seat lightly and stand without pausing.',safety:['Chair must be sturdy and against a wall.','Use a pain-free depth only.'],level1:prescription('6 repetitions',2,40,4,'Every seat contact is controlled.'),level2:prescription('8 repetitions',2,45,5,'Stand without rushing or holding breath.'),level3:prescription('8 slow repetitions',3,50,6,'Keep the same control in the final round.')},
 'wall-push':{name:'Wall push-up',purpose:'Build controlled upper-body support without floor loading.',skills:[7],equipment:['wall-space'],setup:'Use a solid wall, not glass or a door, with clear floor behind.',start:'Place hands at shoulder height and take one small step back.',steps:three('Keep the body in one straight line.','Bend elbows and move the chest gently toward the wall.','Push back until arms are straight without locking hard.'),cues:['Whole body moves together.','Breathe normally.'],mistake:'Hips sagging or hands placed on an unstable surface.',easier:'Stand closer to the wall.',harder:'Stand one small step farther away while control remains unchanged.',safety:['Do not use glass, a door, or unstable furniture.','Stop for wrist, shoulder, or back pain.'],level1:prescription('6 repetitions',2,35,3,'Body stays in one line.'),level2:prescription('8 repetitions',2,40,4,'Every repetition stays smooth.'),level3:prescription('10 repetitions',2,45,5,'Control remains unchanged in the final repetitions.')},
 'heel-slide':{name:'Supine heel slide',purpose:'Practice trunk control with low-demand leg movement.',skills:[8],equipment:[],tags:['floor','controlled'],setup:'Place an exercise mat on a clear floor with enough room to lie down.',start:'Lie on the back with knees bent, feet down, and arms relaxed.',steps:three('Breathe normally and keep hips still.','Slide one heel away only as far as comfortable.','Return it slowly, then change legs.'),cues:['Small smooth movement.','No back arching.'],mistake:'Sliding farther after the hips or back begin to move.',easier:'Slide each heel only half as far.',harder:'Pause for one second at the farthest comfortable point.',safety:['Use a comfortable range only.','Stop for back, hip, or knee pain.'],level1:prescription('4 slides each side',2,25,3,'Hips remain still.'),level2:prescription('6 slides each side',2,30,4,'Movement stays smooth on both sides.'),level3:prescription('8 slides each side',2,35,5,'Control stays unchanged with the pause.')},
 'ankle-rock':{name:'Supported ankle rock',purpose:'Explore comfortable ankle movement without forcing range.',skills:[9],equipment:['wall-space'],setup:'Face a solid wall on a clear floor and place one foot a small step ahead.',start:'Keep the front heel down and rest hands lightly on the wall.',steps:three('Move the front knee forward a small amount.','Keep the heel down and stop before pinching.','Return slowly, finish the repetitions, then switch sides.'),cues:['Comfortable range.','Heel stays down.'],mistake:'Forcing the knee farther after discomfort begins.',easier:'Make the forward movement smaller.',harder:'Pause briefly at the comfortable end of the movement.',safety:['Never force a stretch.','Stop for pinching or pain.'],level1:prescription('6 rocks each side',2,25,3,'Every movement stays comfortable.'),level2:prescription('8 rocks each side',2,30,4,'Heel remains down on every repetition.'),level3:prescription('8 rocks with a pause each side',3,30,5,'Range stays comfortable in every round.')},
 'two-hand-wall-catch':{name:'Wall ball two-hand catch',purpose:'Track a soft ball through a predictable rebound.',skills:[10,11],attributes:['SEE'],equipment:['tennis-ball','wall-space'],tags:['standing','soft-ball'],setup:'Use a soft ball. Stand two big steps from a solid wall, away from people and glass.',start:'Hold the ball at waist height with both hands visible.',steps:three('Throw gently below shoulder height.','Watch the full rebound into both hands.','Reset the feet and count the attempt, including a miss.'),cues:['See the whole bounce.','Finish balanced.'],mistake:'Throwing harder after a miss.',easier:'Allow one floor bounce before catching.',harder:'Vary the gentle target height without adding speed.',safety:['Soft ball only.','Keep people and glass outside the rebound area.'],level1:prescription('8 attempts',2,30,5,'Count every attempt and finish balanced.'),level2:prescription('10 attempts',2,30,5,'Track the full rebound into the hands.'),level3:prescription('10 varied attempts',3,35,6,'Keep tracking quality when target height changes.')},
 'alternate-hand-wall-catch':{name:'Alternating-hand wall catch',purpose:'Coordinate a gentle throw and controlled receiving-hand change.',skills:[10,11,18],attributes:['SEE','REACT'],equipment:['tennis-ball','wall-space'],tags:['standing','soft-ball'],setup:'Use a soft ball at a solid wall, two big steps away from people and glass.',start:'Stand balanced holding the ball in one hand at waist height.',steps:three('Throw gently with the right hand and receive with the left.','Throw gently with the left and receive with the right.','Continue alternating and count every throw, including misses.'),cues:['Soft throw.','See the whole rebound.'],mistake:'Increasing speed before alternating is controlled.',easier:'Catch with two hands, then change the throwing hand.',harder:'Alternate cleanly while keeping the same gentle throw speed.',safety:['Soft ball only.','Do not throw harder to increase difficulty.'],level1:prescription('6 alternating attempts',2,35,5,'Every throw stays gentle.'),level2:prescription('10 alternating attempts',2,40,5,'Hands alternate without increasing speed.'),level3:prescription('12 alternating attempts',3,45,6,'Control remains steady across all rounds.')},
 'find-step-reset':{name:'Find step reset',purpose:'Practice finding a soft ball before moving and resetting.',skills:[16,21],attributes:['RECOVER'],equipment:['tennis-ball','cones'],setup:'Place two flat markers one step to either side on a dry floor with a soft ball.',start:'Stand centered with the ball in one hand and a balanced ready stance.',steps:three('Roll the ball gently toward one marker.','Find it with the eyes, then step and pick it up.','Return to the center balanced before changing sides.'),cues:['Look first.','Finish steady.'],mistake:'Moving before finding the ball or dropping to the knees.',easier:'Place the ball within one easy step.',harder:'Use an adult point cue to choose the side before a gentle roll.',safety:['No diving, sliding, or knee drops.','Use a soft ball and flat markers only.'],level1:prescription('4 rolls each side',2,35,4,'Find the ball before every step.'),level2:prescription('6 alternating rolls',3,40,5,'Return balanced after every roll.'),level3:prescription('8 cued rolls',3,45,6,'Respond to the cue without losing the find-first sequence.')},
 'scan-card-reset':{name:'Scan card and reset',purpose:'Practice an early scan followed by eyes returning to the task.',skills:[17],attributes:['SEE'],equipment:['cones'],setup:'Place two colored cards or flat markers to the left and right; no ball is used.',start:'Stand centered with eyes forward and feet still.',steps:three('Turn the head and name one color.','Return the eyes and head to center.','Reset, then use the other side on the next repetition.'),cues:['Scan early.','Eyes return before the next action.'],mistake:'Turning the feet or rushing the return to center.',easier:'Point to the color instead of saying it.',harder:'Respond to an adult color call without moving the feet.',safety:['No thrown object is used while looking away.','Keep the floor area clear.'],level1:prescription('4 scans each side',2,20,3,'Eyes return to center every time.'),level2:prescription('6 alternating scans',2,25,4,'Feet remain still through each scan.'),level3:prescription('8 cued scans',3,25,5,'Return to center before the next cue.')},
 'sightline-window':{name:'Find the viewing window',purpose:'Practice a small head adjustment to restore sightline.',skills:[24],attributes:['SEE'],equipment:[],setup:'Place a stable chair between the player and a colored floor target; no ball is thrown.',start:'Stand still where the chair partly blocks the target.',steps:three('Look for the target around the chair.','Move the head a small amount until the target is visible.','Name the color, return to center, and repeat.'),cues:['Small head move.','Feet stay quiet.'],mistake:'Climbing, leaning on, or throwing through the chair.',easier:'Move the target farther from the chair.',harder:'Use two target positions and respond to an adult cue.',safety:['Chair must be stable.','No climbing or thrown balls.'],level1:prescription('4 finds each side',2,20,3,'Target is found without moving the feet.'),level2:prescription('6 alternating finds',2,25,4,'Head movement remains small.'),level3:prescription('8 cued finds',3,25,5,'Find the correct target and return to center.')},
 'soft-ball-target-roll':{name:'Soft-ball target roll',purpose:'Practice looking before sending a soft ball to a safe target.',skills:[12,14,25],attributes:['REACT','THINK'],equipment:['tennis-ball','cones'],setup:'Make a wide target gate with two flat markers in a clear area with no person ahead.',start:'Stand or kneel comfortably behind the soft ball with hands ready to roll.',steps:three('Look at the target gate.','Roll the ball gently through the gate.','Walk to collect it and reset behind the start line.'),cues:['Look first.','Roll gently.'],mistake:'Throwing hard or sending the ball before looking.',easier:'Widen the target gate and move closer.',harder:'Narrow the gate slightly without adding speed.',safety:['Soft ball only.','No stick or hard shot is used.'],level1:prescription('6 rolls',2,25,4,'Every ball stays on the floor.'),level2:prescription('8 rolls',2,30,4,'Look before every controlled roll.'),level3:prescription('10 rolls',3,30,5,'Accuracy improves without increasing speed.')},
 'walk-breathe-reset':{name:'Walk breathe reset',purpose:'Finish practice with low-demand recovery and reflection.',skills:[16,28,30],attributes:['RECOVER','COMPETE'],equipment:[],tags:['walking','recovery'],setup:'Clear a quiet path and move equipment outside the walking area.',start:'Stand or sit comfortably and confirm the area is clear.',steps:three('Walk easily with relaxed shoulders.','Stand or sit and take four normal breaths with a gentle exhale.','Name one controlled action and one cue to remember.'),cues:['Finish calm.','Keep breathing normally.'],mistake:'Using breath holding or extra effort to turn recovery into a challenge.',easier:'Sit for the breathing and reflection.',harder:'Use the same recovery after one approved low-demand task.',safety:['Stop for dizziness or discomfort.','This is recovery, not conditioning.'],level1:prescription('90-second walk and 4 breaths',1,0,3,'Finish comfortable and calm.','seconds'),level2:prescription('2-minute walk and 4 breaths',1,0,3,'Finish comfortable and name one useful cue.','seconds'),level3:prescription('2-minute walk and 5 breaths',1,0,4,'Finish comfortable and describe the reset.','seconds')},
 'rush-depth-choice':{name:'Rush depth choice',purpose:'Learn when a goalie may hold position or adjust depth using a seated scenario.',skills:[13,20,26],attributes:['THINK'],equipment:[],tags:['seated','concept'],setup:'Sit comfortably with the reviewed rush-depth diagram visible on screen.',start:'Read the attacker position, puck location, and marked goalie position.',steps:three('Identify what information is already clear.','Choose hold position or controlled depth change.','Read the explanation and say which cue changed the choice.'),cues:['Read before moving.','One clue is not certainty.'],mistake:'Treating every rush picture as the same decision.',easier:'Ask an adult to read the scenario and choices aloud.',harder:'Compare two diagrams with one changed attacker cue.',safety:['Seated concept task only.','Do not act out on-ice movements off ice.'],level1:prescription('3 scenarios',1,0,4,'Explain one useful cue.'),level2:prescription('4 scenarios',1,0,5,'Identify the cue before choosing.'),level3:prescription('5 paired scenarios',1,0,6,'Explain why the changed cue changes or preserves the decision.')},
 'release-cue-choice':{name:'Release cue choice',purpose:'Distinguish a useful release cue from an early fake in a seated scenario.',skills:[18,20],attributes:['REACT','THINK'],equipment:[],tags:['seated','concept'],setup:'Sit with the reviewed release-sequence cards visible on screen.',start:'Begin at the first frame with hands relaxed and no physical imitation.',steps:three('Look at the puck and the visible release information.','Choose wait or respond for the shown frame.','Read the explanation and identify the useful cue.'),cues:['Read the release.','Do not react to every fake.'],mistake:'Using shoulder movement alone as proof of release.',easier:'Use two frames and one obvious release cue.',harder:'Compare three frames where only the release timing changes.',safety:['Seated concept task only.','No drop or save movement is performed.'],level1:prescription('3 scenarios',1,0,4,'Name the useful release cue.'),level2:prescription('4 scenarios',1,0,5,'Avoid choosing from shoulder motion alone.'),level3:prescription('5 paired scenarios',1,0,6,'Explain the timing difference between fake and release.')},
 'pattern-clue-choice':{name:'Pattern clue choice',purpose:'Use repeated clues without turning one example into certainty.',skills:[19,27],attributes:['THINK'],equipment:[],tags:['seated','concept'],setup:'Sit with three reviewed play cards shown in sequence.',start:'Read the first card and keep the answer open until all cards are viewed.',steps:three('Name one clue from each card.','Identify whether a pattern repeats.','Choose watch, prepare, or not enough evidence and explain why.'),cues:['Use repeated clues.','Keep uncertainty honest.'],mistake:'Calling one example a guaranteed pattern.',easier:'Use two cards with one repeated visible clue.',harder:'Use four cards including one exception.',safety:['Seated concept task only.','No prediction is presented as certainty.'],level1:prescription('2 card sets',1,0,4,'Separate one clue from a pattern.'),level2:prescription('3 card sets',1,0,5,'Identify repeated and non-repeated clues.'),level3:prescription('4 card sets',1,0,6,'Explain the pattern and the exception without certainty language.')},
 'call-before-roll':{name:'Call before the roll',purpose:'Practice a short communication cue before a controlled pass.',skills:[12,15,25],attributes:['COMPETE','THINK'],equipment:['tennis-ball','cones'],setup:'Create a wide target gate with flat markers in a clear area; use a soft ball.',start:'Stand or kneel behind the ball and look at the target.',steps:three('Say one short call such as yours.','Roll the ball gently through the gate.','Collect it safely and reset before the next call.'),cues:['Look then call.','One clear word.'],mistake:'Calling after the ball is already moving.',easier:'Point to the target, say the call, then hand-roll from closer.',harder:'An adult changes between two safe target gates before the call.',safety:['Soft ball only.','No person stands in the target gate.'],level1:prescription('6 calls and rolls',2,25,4,'The call comes before every roll.'),level2:prescription('8 calls and rolls',2,30,5,'Call stays clear and roll stays gentle.'),level3:prescription('10 cued calls and rolls',3,30,6,'Choose the called target without increasing speed.')},
 'controlled-march-stop':{name:'Controlled march and stop',purpose:'Practice a quick start followed by an intentional safe stop indoors.',skills:[3,6],attributes:['MOVE'],equipment:['cones'],setup:'Place two flat markers three walking steps apart on a dry clear floor.',start:'Stand tall behind the first marker with clear space beyond the second.',steps:three('March quickly toward the second marker without running.','Slow the feet before reaching the marker.','Stop balanced, walk back, and reset.'),cues:['Quick feet.','Easy controlled stop.'],mistake:'Turning the march into a sprint or stopping against a wall.',easier:'Use slower marching and a shorter distance.',harder:'Respond to an adult start cue while keeping the same safe stop.',safety:['No hallway sprinting or approach toward a wall.','Reduce speed immediately if control changes.'],level1:prescription('4 marches',2,35,4,'Every stop finishes balanced.'),level2:prescription('5 marches',3,40,5,'Speed changes without losing the stop.'),level3:prescription('6 cued marches',3,45,6,'Respond to the cue and preserve the stopping space.')},
 'chaos-update-choice':{name:'Broken-play update',purpose:'Practice updating a read when a seated diagram changes.',skills:[22,26],attributes:['REACT','THINK'],equipment:[],tags:['seated','concept'],setup:'Sit with a reviewed two-frame broken-play diagram visible.',start:'Study the first frame and identify the puck and nearest threat.',steps:three('Describe what changed in the second frame.','Choose the safest new focus from the provided options.','Read the explanation and name the new evidence.'),cues:['Update what changed.','Do not chase the old picture.'],mistake:'Keeping the first answer after the evidence changes.',easier:'Use a single obvious change between two frames.',harder:'Use three frames with one irrelevant change.',safety:['Seated concept task only.','Do not act out floor drops or collisions.'],level1:prescription('3 scenarios',1,0,4,'Name the changed evidence.'),level2:prescription('4 scenarios',1,0,5,'Update the choice after each change.'),level3:prescription('5 multi-frame scenarios',1,0,6,'Separate useful changes from irrelevant ones.')},
 'behind-net-threat-choice':{name:'Behind-net threat choice',purpose:'Practice tracking the carrier and identifying the front-side threat in a seated diagram.',skills:[23,26],attributes:['THINK','SEE'],equipment:[],tags:['seated','concept'],setup:'Sit with a reviewed behind-net rink diagram visible on screen.',start:'Identify the puck carrier and the marked front-side player.',steps:three('Follow the carrier position across the diagram.','Identify the immediate front-side passing threat.','Choose the safe attention cue and read the explanation.'),cues:['Track the carrier.','Check the front threat.'],mistake:'Watching only the carrier and ignoring the available pass.',easier:'Use one carrier and one clearly marked threat.',harder:'Compare two options where the front threat changes sides.',safety:['Seated concept task only.','No on-ice movement is assigned.'],level1:prescription('3 scenarios',1,0,4,'Identify carrier and front threat.'),level2:prescription('4 scenarios',1,0,5,'Update when the threat changes side.'),level3:prescription('5 paired scenarios',1,0,6,'Explain which visible cue changed the attention priority.')},
 'quality-reset-reflection':{name:'Quality reset reflection',purpose:'Recognize when control drops and choose rest or an easier version.',skills:[28,29,30],attributes:['COMPETE','RECOVER'],equipment:[],tags:['seated','concept','recovery'],setup:'Sit with three reviewed short practice-result examples visible.',start:'Read the first example and identify whether control stayed the same.',steps:three('Choose continue, rest, or easier version.','Name the evidence for the choice.','Read the feedback and state one reset cue.'),cues:['Quality before speed.','Choose rest when control drops.'],mistake:'Treating completion speed as proof of good work.',easier:'Use two examples with an obvious control change.',harder:'Use four examples including a stable late repetition.',safety:['Seated reflection only.','Never encourage pushing through pain or dizziness.'],level1:prescription('3 examples',1,0,4,'Choose a safe response for each example.'),level2:prescription('4 examples',1,0,5,'Name the control evidence before choosing.'),level3:prescription('5 examples',1,0,6,'Distinguish fatigue from one ordinary miss without diagnosing injury.')},
};

export const candidateActivityVersions=Object.entries(base).map(([id,value])=>candidate(id,value));
